<?php



// .dat, .iit upload..... exam status for .dat/.iit uploads

//Parameters Required:  CollegeID and ExamID
/*
Available Status:
 Status_number  Description

     1			IMK-Incomplete
     2			Date and time to upload is over
     3			Can upload  (CAN SCAN)
     4			Webprocessing is Pending
     5			Campus Result Generated but Final Ranking not generated yet
     6			Final Ranking Generated by Exam Admin
     7			Reupload.   (CAN SCAN)
*/

$con = new mysqli('localhost', 'root', 'Sciladmin@123', 'esaplive');

 $status=get_status($con,1,120);   //Parameters = $con,$exam_id,$this_campus_id

function get_status($con,$exam_id,$this_campus_id)
{

    $status="3-upload"; // default status.... other conditions will override status and returns the status..
    $current_date=current_date_y_m_d();
    $current_time=current_time_12_hour_format_h_m_s();

	
	$res=$con->query("select * from 1_exam_admin_create_exam where sl='$exam_id'");
	$row=mysqli_fetch_array($res);
   
    $omr_scanning_type=$row['omr_scanning_type'];
	$status_serialized_array=$row['status_serialized'];	
	$subject_string_final=$row['subject_string_final'];
	$to_from_range=$row['to_from_range'];
	$total_questions=$row['total_questions'];
	$mark_file_long_string=$row['mark_file_long_string'];
	$mark_file_rows=$row['mark_file_rows'];
	$key_answer_file_long_string=$row['key_answer_file_long_string'];
	$last_date_to_upload=$row['last_date_to_upload'];
	$last_time_to_upload=$row['last_time_to_upload'];
	$is_college_id_mobile_uploaded=$row['is_college_id_mobile_uploaded'];
	$result_generated1_no0=$row['result_generated1_no0'];

	
	if($omr_scanning_type=="non_advanced")
	{if(($subject_string_final=="")||($to_from_range=="")||($total_questions==0)||($mark_file_long_string=="")||($mark_file_rows==0)||($key_answer_file_long_string==""))
	{ $status= "1-i-m-k_incomplete"; return $status;exit;}}
	if($omr_scanning_type=="advanced")
	{if(($key_answer_file_long_string=="")){$status= "1-ias_incomplete"; return $status;exit;}}

	if($last_date_to_upload !="")
	{ if($current_date>$last_date_to_upload){$status= "2-date_over"; return $status; exit;}
	else
	if($current_date==$last_date_to_upload){if($current_time > $last_time_to_upload){$status= "2-date_over"; return $status; exit;}}}


    $is_college_id_mobile_uploaded_array=explode(",",$is_college_id_mobile_uploaded);
    if(in_array($this_campus_id, $is_college_id_mobile_uploaded_array))
    {
    	$status="4-webprocessing_pending";
    }


   $res_recompute=$con->query("select * from 1_exam_recompute_request_campus_id where campus_id='$this_campus_id' and sl='$exam_id'");
   $count_recompute=mysqli_num_rows($res_recompute);

   if($count_recompute!=0)
   {

   	$row_recompute=mysqli_fetch_array($res_recompute);
   	$is_uploaded=$row_recompute['is_uploaded'];
   	if($is_uploaded=="0"){
   		$recompute_status="should_upload_again"; //Reupload
   	}
   	else
   		if($is_uploaded=="1")
   		{
   			//echo "5-uploaded"; 
        $status="5-uploaded";
   		}
   }


 
										if($status_serialized_array !="")
										{ $status_non_serialized_array=unserialize($status_serialized_array);
									       if(isset($status_non_serialized_array[$this_campus_id]))
										   {
											   $success_or_danger="success";  //uploaded
										   }
										   else{
											     $success_or_danger="danger"; //upload
										       }
											 
										}
										else
										{
											$success_or_danger="danger"; //upload
										}



										if($recompute_status=="should_upload_again")
                                            {
                                                  $status="7-Reupload";
                                            }
                                         else
                                            {
											if($success_or_danger=="success"){$status="5-uploaded";}
                                             if($success_or_danger=="danger"){$status="3-upload";}


                                            }

                                            if($result_generated1_no0==1)
                                            {
                                            	$status="6-Final_Ranking_Generated";
                                            }

                 // get initial sl ends



  return $status;
}//function ends



 function current_date_d_m_y()  // display date    D-M-Y
 {
    $timezone = new DateTimeZone("Asia/Kolkata" );
    $date = new DateTime();
    $date->setTimezone($timezone );
    $date=$date->format('d-m-Y');
 	return $date;
 }

  function current_date_y_m_d() // sorting date   Y-M-D
 {
    $timezone = new DateTimeZone("Asia/Kolkata" );
    $date = new DateTime();
    $date->setTimezone($timezone );
    $date=$date->format('Y-m-d');
 	return $date;
 }
 function current_time_12_hour_format_h_m_s()
 {

    $timezone = new DateTimeZone("Asia/Kolkata" );
    $date = new DateTime();
    $date->setTimezone($timezone );
    $date=$date->format('H:i:s');
 	return $date;    // variable name is data... but it will return Time

 }



